{
	"id": "ALAS2PYTHON3.8-2023-008",
	"advisories": [
		{
			"content": {
				"id": "ALAS2PYTHON3.8-2023-008",
				"title": "Amazon Linux 2 - Python3.8 2.0 - ALAS2PYTHON3.8-2023-008: medium priority package update for python38",
				"description": "Package updates are available for Amazon Linux 2 - Python3.8 that fix the following vulnerabilities:\nCVE-2020-14422:\n\tA vulnerability was found in the way the ipaddress python module computes hash values in the IPv4Interface and IPv6Interface classes. This flaw allows an attacker to create many dictionary entries, due to the performance of a dictionary containing the IPv4Interface or IPv6Interface objects, possibly resulting in a denial of service. The highest threat from this vulnerability is to system availability.\n\nCVE-2019-20907:\n\tA flaw was found in python. In Lib/tarfile.py an attacker is able to craft a TAR archive leading to an infinite loop when opened by tarfile.open, because _proc_pax lacks header validation.\n",
				"severity": [
					{
						"type": "vendor",
						"source": "linux-security@amazon.com",
						"vendor": "medium"
					}
				],
				"references": [
					{
						"source": "linux-security@amazon.com",
						"url": "http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-20907"
					},
					{
						"source": "linux-security@amazon.com",
						"url": "http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-14422"
					},
					{
						"source": "linux-security@amazon.com",
						"url": "https://alas.aws.amazon.com/AL2/ALASPYTHON3.8-2023-008.html"
					}
				]
			},
			"ecosystems": [
				"amazon:2"
			]
		}
	],
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2019-20907",
				"references": [
					{
						"source": "linux-security@amazon.com",
						"url": "http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-20907"
					}
				]
			},
			"ecosystems": [
				"amazon:2"
			]
		},
		{
			"content": {
				"id": "CVE-2020-14422",
				"references": [
					{
						"source": "linux-security@amazon.com",
						"url": "http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-14422"
					}
				]
			},
			"ecosystems": [
				"amazon:2"
			]
		}
	],
	"detection": [
		{
			"ecosystem": "amazon:2",
			"criteria": {
				"operator": "OR",
				"criterions": [
					{
						"vulnerable": true,
						"package": {
							"name": "python38",
							"architectures": [
								"x86_64"
							],
							"repositories": [
								"amzn2extra-python3.8"
							]
						},
						"affected": {
							"type": "rpm",
							"range": [
								{
									"lt": "0:3.8.5-1.amzn2.0.1"
								}
							],
							"fixed": [
								"0:3.8.5-1.amzn2.0.1"
							]
						}
					},
					{
						"vulnerable": true,
						"package": {
							"name": "python38-debug",
							"architectures": [
								"x86_64"
							],
							"repositories": [
								"amzn2extra-python3.8"
							]
						},
						"affected": {
							"type": "rpm",
							"range": [
								{
									"lt": "0:3.8.5-1.amzn2.0.1"
								}
							],
							"fixed": [
								"0:3.8.5-1.amzn2.0.1"
							]
						}
					},
					{
						"vulnerable": true,
						"package": {
							"name": "python38-debuginfo",
							"architectures": [
								"x86_64"
							],
							"repositories": [
								"amzn2extra-python3.8"
							]
						},
						"affected": {
							"type": "rpm",
							"range": [
								{
									"lt": "0:3.8.5-1.amzn2.0.1"
								}
							],
							"fixed": [
								"0:3.8.5-1.amzn2.0.1"
							]
						}
					},
					{
						"vulnerable": true,
						"package": {
							"name": "python38-devel",
							"architectures": [
								"x86_64"
							],
							"repositories": [
								"amzn2extra-python3.8"
							]
						},
						"affected": {
							"type": "rpm",
							"range": [
								{
									"lt": "0:3.8.5-1.amzn2.0.1"
								}
							],
							"fixed": [
								"0:3.8.5-1.amzn2.0.1"
							]
						}
					},
					{
						"vulnerable": true,
						"package": {
							"name": "python38-libs",
							"architectures": [
								"x86_64"
							],
							"repositories": [
								"amzn2extra-python3.8"
							]
						},
						"affected": {
							"type": "rpm",
							"range": [
								{
									"lt": "0:3.8.5-1.amzn2.0.1"
								}
							],
							"fixed": [
								"0:3.8.5-1.amzn2.0.1"
							]
						}
					},
					{
						"vulnerable": true,
						"package": {
							"name": "python38-test",
							"architectures": [
								"x86_64"
							],
							"repositories": [
								"amzn2extra-python3.8"
							]
						},
						"affected": {
							"type": "rpm",
							"range": [
								{
									"lt": "0:3.8.5-1.amzn2.0.1"
								}
							],
							"fixed": [
								"0:3.8.5-1.amzn2.0.1"
							]
						}
					},
					{
						"vulnerable": true,
						"package": {
							"name": "python38-tkinter",
							"architectures": [
								"x86_64"
							],
							"repositories": [
								"amzn2extra-python3.8"
							]
						},
						"affected": {
							"type": "rpm",
							"range": [
								{
									"lt": "0:3.8.5-1.amzn2.0.1"
								}
							],
							"fixed": [
								"0:3.8.5-1.amzn2.0.1"
							]
						}
					},
					{
						"vulnerable": true,
						"package": {
							"name": "python38-tools",
							"architectures": [
								"x86_64"
							],
							"repositories": [
								"amzn2extra-python3.8"
							]
						},
						"affected": {
							"type": "rpm",
							"range": [
								{
									"lt": "0:3.8.5-1.amzn2.0.1"
								}
							],
							"fixed": [
								"0:3.8.5-1.amzn2.0.1"
							]
						}
					}
				]
			}
		}
	],
	"data_source": {
		"id": "amazon",
		"raws": [
			"vuls-data-raw-amazon/2/extras/python3.8/2023/ALAS2PYTHON3.8-2023-008.json"
		]
	}
}
